const questions = [
    { question: 'Wie heißt du?', options: ['Ich heiße Tom', 'Er ist Tom', 'Sie heißt Tom'], answer: 'Ich heiße Tom' },
    { question: 'Wo wohnst du?', options: ['Ich wohne in Berlin', 'Er wohnt hier', 'Sie wohnen'], answer: 'Ich wohne in Berlin' },
    { question: 'Wie alt bist du?', options: ['Ich bin 20 Jahre alt', 'Er ist 20 Jahre', 'Sie ist alt'], answer: 'Ich bin 20 Jahre alt' },
    { question: 'Was machst du beruflich?', options: ['Ich bin Student', 'Sie sind Lehrer', 'Er macht Arbeit'], answer: 'Ich bin Student' },
    { question: 'Wie spät ist es?', options: ['Es ist 10 Uhr', 'Ich bin 10', 'Heute ist Montag'], answer: 'Es ist 10 Uhr' },
    { question: 'Was ist dein Lieblingsessen?', options: ['Pizza', 'Auto', 'Haus'], answer: 'Pizza' },
    { question: 'Wie geht es dir?', options: ['Gut, danke', 'Ich bin Hunger', 'Ich wohne'], answer: 'Gut, danke' },
    { question: 'Was machst du gern?', options: ['Ich lese gern', 'Ich bin Schule', 'Ich gehe zur Arbeit'], answer: 'Ich lese gern' },
    { question: 'Welche Farbe hat der Himmel?', options: ['Blau', 'Apfel', 'Heiß'], answer: 'Blau' },
    { question: 'Was ist dein Hobby?', options: ['Fußball spielen', 'Ich habe Schule', 'Ich esse'], answer: 'Fußball spielen' },
    { question: 'Woher kommst du?', options: ['Ich komme aus Marokko', 'Ich bin Berlin', 'Ich wohne'], answer: 'Ich komme aus Marokko' },
    { question: 'Wie heißt Ihre Mutter?', options: ['Sie heißt Anna', 'Ich heiße Anna', 'Er heißt Anna'], answer: 'Sie heißt Anna' },
    { question: 'Was ist das?', options: ['Das ist ein Tisch', 'Ich bin Tisch', 'Das ist alt'], answer: 'Das ist ein Tisch' },
    { question: 'Wann hast du Geburtstag?', options: ['Am ersten März', 'Ich bin alt', 'Ich gehe'], answer: 'Am ersten März' },
    { question: 'Was trägst du gern?', options: ['Ich trage gern Jeans', 'Ich bin Jeans', 'Ich wohne in Jeans'], answer: 'Ich trage gern Jeans' },
    { question: 'Was machst du am Wochenende?', options: ['Ich gehe spazieren', 'Ich arbeite Schule', 'Ich bin Arbeit'], answer: 'Ich gehe spazieren' },
    { question: 'Was isst du zum Frühstück?', options: ['Brot und Käse', 'Ich bin Käse', 'Ich esse Schule'], answer: 'Brot und Käse' },
    { question: 'Was machst du abends?', options: ['Ich sehe fern', 'Ich bin Abend', 'Ich mache Morgen'], answer: 'Ich sehe fern' },
    { question: 'Wie ist das Wetter?', options: ['Es ist sonnig', 'Ich bin Wetter', 'Es ist Monat'], answer: 'Es ist sonnig' },
    { question: 'Was trinkst du?', options: ['Ich trinke Wasser', 'Ich esse Wasser', 'Ich wohne Wasser'], answer: 'Ich trinke Wasser' },
    { question: 'Was ist dein Lieblingsfach?', options: ['Mathematik', 'Kuh', 'Auto'], answer: 'Mathematik' },
    { question: 'Was machst du nach der Schule?', options: ['Ich mache Hausaufgaben', 'Ich bin Schule', 'Ich esse Schule'], answer: 'Ich mache Hausaufgaben' },
    { question: 'Was ist dein Lieblingsfilm?', options: ['Inception', 'Apfel', 'Wasser'], answer: 'Inception' },
    { question: 'Was ist dein Lieblingsbuch?', options: ['Harry Potter', 'Haus', 'Fenster'], answer: 'Harry Potter' },
    { question: 'Was machst du in den Ferien?', options: ['Ich reise', 'Ich gehe Schule', 'Ich bin Ferien'], answer: 'Ich reise' },
    { question: 'Was ist deine Lieblingsmusik?', options: ['Pop', 'Buch', 'Lehrer'], answer: 'Pop' },
    { question: 'Was möchtest du werden?', options: ['Ingenieur', 'Apfel', 'Tisch'], answer: 'Ingenieur' },
    { question: 'Wie viele Sprachen sprichst du?', options: ['Drei', 'Apfel', 'Haus'], answer: 'Drei' },
    { question: 'Was machst du heute?', options: ['Ich lerne Deutsch', 'Ich bin Schule', 'Ich habe'], answer: 'Ich lerne Deutsch' },
    { question: 'Was möchtest du trinken?', options: ['Wasser bitte', 'Ich bin Wasser', 'Trinken'], answer: 'Wasser bitte' },
  ];
  
  export default questions;
  